# Generated by Django 3.0.5 on 2020-05-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='nombre_personnes',
            field=models.IntegerField(),
        ),
    ]
